services:
  web:
    build: .
    container_name: kadi4mat
    volumes:
      - kadi4mat-data:/opt/kadi
    depends_on:
      - postgres
    links:
      - postgres
      - redis
      - elastic
    ports:
      - "8002:443"

  postgres:
    image: postgres:15
    container_name: kadi-pg
    environment:
      POSTGRES_USER: kadi
      POSTGRES_PASSWORD: kadi
      POSTGRES_DB: kadi
    volumes:
      - kadi-db-data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: kadi-redis
    volumes:
      - kadi-redis:/data

  elastic:
    image: elasticsearch:8.13.4
    container_name: elasticsearch
    volumes:
      - kadi-elastic:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

volumes:
  kadi4mat-data:
  kadi-db-data:
  kadi-redis:
  kadi-elastic:
