services:
    rspace-app:
      build: .
      container_name: rspace-app
      volumes:
        -  ./deployment.properties:/etc/rspace/deployment.properties
        -  ./configs/rspace.env:/usr/local/tomcat/bin/setenv.sh
        -  ./configs/tomcat-locate.sh:/usr/libexec/tomcat9/tomcat-locate-java.sh
        -  ./configs/server.xml:/usr/local/tomcat/conf/server.xml
        - rspace-media:/media/rspace
      ports:
        - '8003:8080'
      depends_on:
        prep-container:
          condition: service_completed_successfully
        rspace-db:
          condition: service_healthy
    prep-container:
      image: 'alpine:latest'
      container_name: rspace-prep-container
      volumes:
        - rspace-media:/media/rspace
      command: >
        mkdir -pv
          /media/rspace/archive
          /media/rspace/archives
          /media/rspace/backup
          /media/rspace/download
          /media/rspace/file_store
          /media/rspace/FTsearchIndices
          /media/rspace/indices
          /media/rspace/jmelody
          /media/rspace/logs-audit
          /media/rspace/LuceneFTsearchIndices
          /media/rspace/tomcat-tmp
    rspace-db:
      image: 'mariadb:lts-jammy'
      container_name: rspace-db
      volumes:
        - rspace-db:/var/lib/mysql
        - ./configs/db-config.cnf:/etc/alternatives/my.cnf
        - ./templates/db-template.sql:/docker-entrypoint-initdb.d/import.sql
      environment:
          MARIADB_ROOT_PASSWORD: rspacedocker
          MARIADB_DATABASE: rspace
          MARIADB_USER: rspacedocker
          MARIADB_PASSWORD: rspacedocker
      healthcheck:
        test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
        start_period: 10s
        interval: 10s
        timeout: 5s
        retries: 5

volumes:
  rspace-media:
  rspace-db:
