services:
  db:
    image: postgres:16
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - chemotion_db:/var/lib/postgresql/data/

  msconvert:
    image: ptrxyz/chemotion:msconvert-1.10.2
    hostname: msconvert
    volumes:
      - spectra:/shared:rw

  spectra:
    image: ptrxyz/chemotion:spectra-1.10.2
    hostname: spectra
    volumes:
      - spectra:/shared:rw
    depends_on:
      - msconvert

  worker:
    image: ptrxyz/chemotion:eln-1.10.2
    environment:
      - CONFIG_ROLE=worker
      - SECRET_KEY_BASE=pleasechangeme
    depends_on:
      - db
      - eln
      - spectra
    volumes:
      - chemotion_data:/chemotion/data/
      - chemotion:/chemotion/app


  eln:
    image: ptrxyz/chemotion:eln-1.10.2
    environment:
      - CONFIG_ROLE=eln
      - SECRET_KEY_BASE=pleasechangeme
    depends_on:
      - db
      - spectra
    volumes:
      - chemotion_data:/chemotion/data/
      - chemotion:/chemotion/app
    ports:
      - 8004:4000


  ketchersvc:
    image: ptrxyz/chemotion:ketchersvc-1.10.2
    environment:
      - CONFIG_KETCHER_URL=http://eln:4000/ketcher/
    init: true
    depends_on:
      eln:
        condition: service_healthy


  converter:
    image: ptrxyz/chemotion:converter-1.10.2
    environment:
      - SECRET_KEY=imsupersecretandwanttobechanged


volumes:
  chemotion:
    name: chemotion_app
  chemotion_data:
    name: chemotion_data
  chemotion_db:
    name: chemotion_db
  spectra:
    name: chemotion_spectra
